name = "Skyrmions"
uuid = "1ccad2fe-a5c3-464e-b06e-022e005d04e0"
authors = ["Chris Halcrow"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
